kind: Service
apiVersion: v1
metadata:
  name: flow
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8090
    nodePort: 8090

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow
  labels:
    app: flow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flow
  template:
    metadata:
      labels:
        app: flow
    spec:
      containers:
      - name: flow
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8090
